version: '3'

services:
  node:
    env_file:
      - .env
    image: "node:18"
    container_name: node_api
    working_dir: /index
    volumes:
      - .:/index
    ports:
      - "80:3000"
    command: "npm start"
    depends_on:
      - mongo

  mongo:
    env_file:
      - .env
    image: mongo

    restart: always
