version: '3'

services:
  node:
    env_file:
      - .env
    image: "node:18"
    container_name: node_api
    working_dir: /index
    volumes:
      - .:/index
    ports:
      - "80:3000"
    command: "npm start"

  mongo:
    env_file:
      - .env
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
